config/routes.rb
Rails.application.routes.draw do
  resources :users, except: [:new, :edit] do
    collection do
      match 'upload', via: [:get, :post]
    end
  end

  root 'users#index'
end

app/views/layouts/_menu.html.slim
.title-bar data-responsive-toggle="menu" data-hide-for="large"
  button.menu-icon type="button" data-toggle="menu-nav"

#menu-nav.off-canvas.position-left.reveal-for-large[data-off-canvas]
  ul.vertical.menu data-responsive-menu="drilldown medium-accordion"
    .grid-container
      .grid-x.grid-padding-x
        .cell.auto
          span
            i.fi-photo style="font-size: 100px;"
          .text-center
            h4 Username
    li
      = link_to "Home", root_path
    li
      = link_to "Employees", users_path
    li
      = link_to "Upload Employees", upload_users_path

app/views/layouts/_messages.html.slim
.grid-container
  .grid-x.grid-padding-x
    .cell.small-12
      - flash.each do |name, msg|
        - if msg.is_a?(String)
          div[class="callout #{name.to_s == :notice.to_s ? "success" : "alert"}" data-closable]
            = msg
            button.close-button[aria-label="Dismiss" type="button" data-close]
              span aria-hidden="true" &times;
        - elsif msg.is_a?(Array)
          div[class="callout #{name.to_s == :notice.to_s ? "success" : "alert"}" data-closable]
            ul
              - msg.each do |m|
                li = m
            button.close-button[aria-label="Dismiss" type="button" data-close]
              span aria-hidden="true" &times;

app/views/layouts/application.html.slim
- app_name = Rails.application.class.module_parent_name
doctype html
html
  head
    meta[name="viewport" content="width=device-width, initial-scale=1.0"]
    meta charset="utf-8"
    title = app_name.underscore.titleize
    == csrf_meta_tags
    == csp_meta_tag

    == stylesheet_pack_tag "application", :media => 'all', 'data-turbolinks-track' => 'reload'
    == javascript_pack_tag "application", 'data-turbolinks-track' => 'reload'

  body
    .off-canvas-wrapper
      == render 'layouts/menu'

      .off-canvas-content[data-off-canvas-content]
        == render 'layouts/messages'

        == yield